apiVersion: 1

deleteDatasources:
  - name: PostgreSQL
    uid: PCC52D03280B7034C

prune: true

datasources:
  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
